### ISSUE TITLE
Concerns/discussion thread

### ISSUE THREAD

**Issue by MKRhere** [feltcoop/why-svelte#1]
First of all, pretty good writeup. I wanted to add our discoveries and concerns.

We tried adopting Svelte as our framework for a medium-sized application to check the depth. While most things worked, I had to write some Rollup plugins myself to help Svelte, and Rollup's documentation on plugins is very hard to understand. While not directly caused by Svelte, it's worth looking at the community around it. Besides, Rich is the genius author behind both.

While looking at shortcomings of Svelte itself, I'd say the first thing is the reassignment pattern. FP-ers like me will cringe at mutation, but let's assume it's okay. Svelte is its own language. But that's the tip of the iceberg. Svelte components don't seem to be first-class; you cannot pass around components very flexibly, you cannot take a component as a parameter, cannot pass CSS classes between components, cannot do Higher Order Components.

Some of these are absent-by-design, and complex to have with Svelte's automatic assignment-based reactivity. I'd say that's the flaw. While a great framework for web apps, these concerns stopped us from adopting Svelte full-time on all our apps.

I'm also not a fan of compilers-needed mentality in general. I'm more tolerant of Svelte than other things (React, Vue, where the compiler is bullshit and completely useless), since the Svelte compiler actually does useful things (I have the same opinion on TypeScript). I love the idea of actual reactivity, rather than re-render + diff based solutions like React.

However, no solution is perfect. I'm exploring the idea of purely runtime-based reactivity in a new solution. Maybe it works, maybe it doesn't. If I remember, I'll try to update here if/when I'm ready :)

**Comment by ryanatkn** [comment]
Thank you!

> Svelte components don't seem to be first-class; you cannot pass around components very flexibly, you cannot take a component as a parameter, cannot pass CSS classes between components, cannot do Higher Order Components.

It's true that Svelte does not allow you to map over children like React, but its [slot API](https://svelte.dev/docs#slot) and [`<svelte:component>`](https://svelte.dev/docs#svelte_component) has simiarly powerful composition. You can pass component constructors as props and instantiate them, and use slots and their let bindings for high order composition. It sounds like you're thinking in virtual DOM idioms instead of Svelte's.

There are some proposals to improve programmatic access to slots like ["A way to see if slot prop is present"](https://github.com/sveltejs/svelte/issues/2106).

The template language's restrictions compared to JavaScript/JSX-built views are part of Svelte's performance story. It's able to optimize things ahead of time that are impossible with dynamic code because of the constraints. Here's a couple tweets from the author about that -

1 - <https://twitter.com/Rich_Harris/status/1224414679021301761>

2 - <https://twitter.com/Rich_Harris/status/948231770725605377>

**Comment by pngwn** [comment]
@MKRhere This doesn't make any sense to me:

>Svelte components don't seem to be first-class; you cannot pass around components very flexibly, you cannot take a component as a parameter, cannot pass CSS classes between components, cannot do Higher Order Components.

Svelte components are just Classes, you can do anything with them that you can do with Classes. You can pass them ass parameters/ props, you can do Higher-Order Components (although it isn't an approach we encourage, there are better patterns to achieve similar things in Svelte). Passing css classes also isn't something generally encourage as style encapsulation is an important part of Svelte's model. You can achieve a similar end via a few different methods. You can pretty much do the same with instances. (although this is arguable less useful), instances are just objects. The rules of Javascript apply here, any constraints in that regard come from the language not the framework.

However, Svelte *isn't* React or Vue or any other framework, the same approach will not always work and given that Svelte has very different constraints and approach that works well in another framework is not suitable with Svelte. Trying to apply approaches use with other frameworks to Svelte will invariably end in frustration.

**Comment by MKRhere** [comment]
Thank you!

My frustration is mainly from Svelte's choices that are very un-JavaScript-like. It doesn't have to be "like React/Vue". React is React because it doesn't restrict what you can do with JavaScript for the most part. It's just common FP practice to fold/map.

> You can achieve a similar end via a few different methods

I'm sure; Svelte is no less powerful than any other framework. If it needs done, it's doable. I was only pointing out in what ways it has been unintuitive to me and similarly experienced developers, and we'd prefer not to retrain in the direction Svelte has chosen. It's a perfectly fine option for many developers I've spoken with.

**Comment by pngwn** [comment]
These are valid comments. I think it is worth noting that svelte didn’t choose a non-javascript method for fun or because we think we should redesign the language. The additional constructs, for the most part, are there to allow svelte to more clearly work out exactly what is going on in the code in order to optimise. In short svelte needs a certain amount of information to do what it does and pure javascript is often difficult to analyse in this way. 

But I appreciate your concerns and comments and we try to take all feedback on board where we can. So thank you!
